// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/discount.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DiscountBase_Kind int32

const (
	DiscountBase_UNKNOWN DiscountBase_Kind = 0
	DiscountBase_NORMAL  DiscountBase_Kind = 1
	DiscountBase_NEW     DiscountBase_Kind = 2
	DiscountBase_OUTLET  DiscountBase_Kind = 3
	DiscountBase_MEMBER  DiscountBase_Kind = 4
)

var DiscountBase_Kind_name = map[int32]string{
	0: "UNKNOWN",
	1: "NORMAL",
	2: "NEW",
	3: "OUTLET",
	4: "MEMBER",
}

var DiscountBase_Kind_value = map[string]int32{
	"UNKNOWN": 0,
	"NORMAL":  1,
	"NEW":     2,
	"OUTLET":  3,
	"MEMBER":  4,
}

func (x DiscountBase_Kind) String() string {
	return proto.EnumName(DiscountBase_Kind_name, int32(x))
}

func (DiscountBase_Kind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d27f2fd5df31734b, []int{0, 0}
}

type DiscountBase struct {
	Kind DiscountBase_Kind `protobuf:"varint,1,opt,name=kind,proto3,enum=pb.DiscountBase_Kind" json:"kind,omitempty"`
	// Types that are valid to be assigned to Value:
	//	*DiscountBase_Amount
	//	*DiscountBase_Rate
	Value                isDiscountBase_Value `protobuf_oneof:"value"`
	Message              string               `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Deadline             *timestamp.Timestamp `protobuf:"bytes,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
	IsMember             bool                 `protobuf:"varint,6,opt,name=isMember,proto3" json:"isMember,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DiscountBase) Reset()         { *m = DiscountBase{} }
func (m *DiscountBase) String() string { return proto.CompactTextString(m) }
func (*DiscountBase) ProtoMessage()    {}
func (*DiscountBase) Descriptor() ([]byte, []int) {
	return fileDescriptor_d27f2fd5df31734b, []int{0}
}

func (m *DiscountBase) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscountBase.Unmarshal(m, b)
}
func (m *DiscountBase) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscountBase.Marshal(b, m, deterministic)
}
func (m *DiscountBase) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscountBase.Merge(m, src)
}
func (m *DiscountBase) XXX_Size() int {
	return xxx_messageInfo_DiscountBase.Size(m)
}
func (m *DiscountBase) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscountBase.DiscardUnknown(m)
}

var xxx_messageInfo_DiscountBase proto.InternalMessageInfo

func (m *DiscountBase) GetKind() DiscountBase_Kind {
	if m != nil {
		return m.Kind
	}
	return DiscountBase_UNKNOWN
}

type isDiscountBase_Value interface {
	isDiscountBase_Value()
}

type DiscountBase_Amount struct {
	Amount uint32 `protobuf:"varint,2,opt,name=amount,proto3,oneof"`
}

type DiscountBase_Rate struct {
	Rate float32 `protobuf:"fixed32,3,opt,name=rate,proto3,oneof"`
}

func (*DiscountBase_Amount) isDiscountBase_Value() {}

func (*DiscountBase_Rate) isDiscountBase_Value() {}

func (m *DiscountBase) GetValue() isDiscountBase_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *DiscountBase) GetAmount() uint32 {
	if x, ok := m.GetValue().(*DiscountBase_Amount); ok {
		return x.Amount
	}
	return 0
}

func (m *DiscountBase) GetRate() float32 {
	if x, ok := m.GetValue().(*DiscountBase_Rate); ok {
		return x.Rate
	}
	return 0
}

func (m *DiscountBase) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *DiscountBase) GetDeadline() *timestamp.Timestamp {
	if m != nil {
		return m.Deadline
	}
	return nil
}

func (m *DiscountBase) GetIsMember() bool {
	if m != nil {
		return m.IsMember
	}
	return false
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*DiscountBase) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _DiscountBase_OneofMarshaler, _DiscountBase_OneofUnmarshaler, _DiscountBase_OneofSizer, []interface{}{
		(*DiscountBase_Amount)(nil),
		(*DiscountBase_Rate)(nil),
	}
}

func _DiscountBase_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*DiscountBase)
	// value
	switch x := m.Value.(type) {
	case *DiscountBase_Amount:
		b.EncodeVarint(2<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Amount))
	case *DiscountBase_Rate:
		b.EncodeVarint(3<<3 | proto.WireFixed32)
		b.EncodeFixed32(uint64(math.Float32bits(x.Rate)))
	case nil:
	default:
		return fmt.Errorf("DiscountBase.Value has unexpected type %T", x)
	}
	return nil
}

func _DiscountBase_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*DiscountBase)
	switch tag {
	case 2: // value.amount
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &DiscountBase_Amount{uint32(x)}
		return true, err
	case 3: // value.rate
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.Value = &DiscountBase_Rate{math.Float32frombits(uint32(x))}
		return true, err
	default:
		return false, nil
	}
}

func _DiscountBase_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*DiscountBase)
	// value
	switch x := m.Value.(type) {
	case *DiscountBase_Amount:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Amount))
	case *DiscountBase_Rate:
		n += 1 // tag and wire
		n += 4
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type GetOneRequest struct {
	TenantID             uint64   `protobuf:"varint,1,opt,name=tenantID,proto3" json:"tenantID,omitempty"`
	PrdouctID            uint64   `protobuf:"varint,2,opt,name=prdouctID,proto3" json:"prdouctID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetOneRequest) Reset()         { *m = GetOneRequest{} }
func (m *GetOneRequest) String() string { return proto.CompactTextString(m) }
func (*GetOneRequest) ProtoMessage()    {}
func (*GetOneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d27f2fd5df31734b, []int{1}
}

func (m *GetOneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOneRequest.Unmarshal(m, b)
}
func (m *GetOneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOneRequest.Marshal(b, m, deterministic)
}
func (m *GetOneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOneRequest.Merge(m, src)
}
func (m *GetOneRequest) XXX_Size() int {
	return xxx_messageInfo_GetOneRequest.Size(m)
}
func (m *GetOneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetOneRequest proto.InternalMessageInfo

func (m *GetOneRequest) GetTenantID() uint64 {
	if m != nil {
		return m.TenantID
	}
	return 0
}

func (m *GetOneRequest) GetPrdouctID() uint64 {
	if m != nil {
		return m.PrdouctID
	}
	return 0
}

type GetOneResponse struct {
	// Types that are valid to be assigned to Discount:
	//	*GetOneResponse_DiscountForAll
	//	*GetOneResponse_DiscountForOne
	//	*GetOneResponse_DiscountForSet
	//	*GetOneResponse_DiscountForBuyAForB
	//	*GetOneResponse_DiscountForBuyXGetOne
	//	*GetOneResponse_DiscountForBuyXGetMore
	//	*GetOneResponse_DiscountForBuyXGetTotal
	Discount             isGetOneResponse_Discount `protobuf_oneof:"discount"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GetOneResponse) Reset()         { *m = GetOneResponse{} }
func (m *GetOneResponse) String() string { return proto.CompactTextString(m) }
func (*GetOneResponse) ProtoMessage()    {}
func (*GetOneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d27f2fd5df31734b, []int{2}
}

func (m *GetOneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetOneResponse.Unmarshal(m, b)
}
func (m *GetOneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetOneResponse.Marshal(b, m, deterministic)
}
func (m *GetOneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetOneResponse.Merge(m, src)
}
func (m *GetOneResponse) XXX_Size() int {
	return xxx_messageInfo_GetOneResponse.Size(m)
}
func (m *GetOneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetOneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetOneResponse proto.InternalMessageInfo

type isGetOneResponse_Discount interface {
	isGetOneResponse_Discount()
}

type GetOneResponse_DiscountForAll struct {
	DiscountForAll *DiscountForAll `protobuf:"bytes,1,opt,name=discountForAll,proto3,oneof"`
}

type GetOneResponse_DiscountForOne struct {
	DiscountForOne *DiscountForOne `protobuf:"bytes,2,opt,name=discountForOne,proto3,oneof"`
}

type GetOneResponse_DiscountForSet struct {
	DiscountForSet *DiscountForSet `protobuf:"bytes,3,opt,name=discountForSet,proto3,oneof"`
}

type GetOneResponse_DiscountForBuyAForB struct {
	DiscountForBuyAForB *DiscountForBuyAForB `protobuf:"bytes,4,opt,name=discountForBuyAForB,proto3,oneof"`
}

type GetOneResponse_DiscountForBuyXGetOne struct {
	DiscountForBuyXGetOne *DiscountForBuyXGet `protobuf:"bytes,5,opt,name=discountForBuyXGetOne,proto3,oneof"`
}

type GetOneResponse_DiscountForBuyXGetMore struct {
	DiscountForBuyXGetMore *DiscountForBuyXGet `protobuf:"bytes,6,opt,name=discountForBuyXGetMore,proto3,oneof"`
}

type GetOneResponse_DiscountForBuyXGetTotal struct {
	DiscountForBuyXGetTotal *DiscountForBuyXGet `protobuf:"bytes,7,opt,name=discountForBuyXGetTotal,proto3,oneof"`
}

func (*GetOneResponse_DiscountForAll) isGetOneResponse_Discount() {}

func (*GetOneResponse_DiscountForOne) isGetOneResponse_Discount() {}

func (*GetOneResponse_DiscountForSet) isGetOneResponse_Discount() {}

func (*GetOneResponse_DiscountForBuyAForB) isGetOneResponse_Discount() {}

func (*GetOneResponse_DiscountForBuyXGetOne) isGetOneResponse_Discount() {}

func (*GetOneResponse_DiscountForBuyXGetMore) isGetOneResponse_Discount() {}

func (*GetOneResponse_DiscountForBuyXGetTotal) isGetOneResponse_Discount() {}

func (m *GetOneResponse) GetDiscount() isGetOneResponse_Discount {
	if m != nil {
		return m.Discount
	}
	return nil
}

func (m *GetOneResponse) GetDiscountForAll() *DiscountForAll {
	if x, ok := m.GetDiscount().(*GetOneResponse_DiscountForAll); ok {
		return x.DiscountForAll
	}
	return nil
}

func (m *GetOneResponse) GetDiscountForOne() *DiscountForOne {
	if x, ok := m.GetDiscount().(*GetOneResponse_DiscountForOne); ok {
		return x.DiscountForOne
	}
	return nil
}

func (m *GetOneResponse) GetDiscountForSet() *DiscountForSet {
	if x, ok := m.GetDiscount().(*GetOneResponse_DiscountForSet); ok {
		return x.DiscountForSet
	}
	return nil
}

func (m *GetOneResponse) GetDiscountForBuyAForB() *DiscountForBuyAForB {
	if x, ok := m.GetDiscount().(*GetOneResponse_DiscountForBuyAForB); ok {
		return x.DiscountForBuyAForB
	}
	return nil
}

func (m *GetOneResponse) GetDiscountForBuyXGetOne() *DiscountForBuyXGet {
	if x, ok := m.GetDiscount().(*GetOneResponse_DiscountForBuyXGetOne); ok {
		return x.DiscountForBuyXGetOne
	}
	return nil
}

func (m *GetOneResponse) GetDiscountForBuyXGetMore() *DiscountForBuyXGet {
	if x, ok := m.GetDiscount().(*GetOneResponse_DiscountForBuyXGetMore); ok {
		return x.DiscountForBuyXGetMore
	}
	return nil
}

func (m *GetOneResponse) GetDiscountForBuyXGetTotal() *DiscountForBuyXGet {
	if x, ok := m.GetDiscount().(*GetOneResponse_DiscountForBuyXGetTotal); ok {
		return x.DiscountForBuyXGetTotal
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GetOneResponse) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GetOneResponse_OneofMarshaler, _GetOneResponse_OneofUnmarshaler, _GetOneResponse_OneofSizer, []interface{}{
		(*GetOneResponse_DiscountForAll)(nil),
		(*GetOneResponse_DiscountForOne)(nil),
		(*GetOneResponse_DiscountForSet)(nil),
		(*GetOneResponse_DiscountForBuyAForB)(nil),
		(*GetOneResponse_DiscountForBuyXGetOne)(nil),
		(*GetOneResponse_DiscountForBuyXGetMore)(nil),
		(*GetOneResponse_DiscountForBuyXGetTotal)(nil),
	}
}

func _GetOneResponse_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GetOneResponse)
	// discount
	switch x := m.Discount.(type) {
	case *GetOneResponse_DiscountForAll:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DiscountForAll); err != nil {
			return err
		}
	case *GetOneResponse_DiscountForOne:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DiscountForOne); err != nil {
			return err
		}
	case *GetOneResponse_DiscountForSet:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DiscountForSet); err != nil {
			return err
		}
	case *GetOneResponse_DiscountForBuyAForB:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DiscountForBuyAForB); err != nil {
			return err
		}
	case *GetOneResponse_DiscountForBuyXGetOne:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DiscountForBuyXGetOne); err != nil {
			return err
		}
	case *GetOneResponse_DiscountForBuyXGetMore:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DiscountForBuyXGetMore); err != nil {
			return err
		}
	case *GetOneResponse_DiscountForBuyXGetTotal:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DiscountForBuyXGetTotal); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("GetOneResponse.Discount has unexpected type %T", x)
	}
	return nil
}

func _GetOneResponse_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GetOneResponse)
	switch tag {
	case 1: // discount.discountForAll
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DiscountForAll)
		err := b.DecodeMessage(msg)
		m.Discount = &GetOneResponse_DiscountForAll{msg}
		return true, err
	case 2: // discount.discountForOne
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DiscountForOne)
		err := b.DecodeMessage(msg)
		m.Discount = &GetOneResponse_DiscountForOne{msg}
		return true, err
	case 3: // discount.discountForSet
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DiscountForSet)
		err := b.DecodeMessage(msg)
		m.Discount = &GetOneResponse_DiscountForSet{msg}
		return true, err
	case 4: // discount.discountForBuyAForB
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DiscountForBuyAForB)
		err := b.DecodeMessage(msg)
		m.Discount = &GetOneResponse_DiscountForBuyAForB{msg}
		return true, err
	case 5: // discount.discountForBuyXGetOne
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DiscountForBuyXGet)
		err := b.DecodeMessage(msg)
		m.Discount = &GetOneResponse_DiscountForBuyXGetOne{msg}
		return true, err
	case 6: // discount.discountForBuyXGetMore
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DiscountForBuyXGet)
		err := b.DecodeMessage(msg)
		m.Discount = &GetOneResponse_DiscountForBuyXGetMore{msg}
		return true, err
	case 7: // discount.discountForBuyXGetTotal
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DiscountForBuyXGet)
		err := b.DecodeMessage(msg)
		m.Discount = &GetOneResponse_DiscountForBuyXGetTotal{msg}
		return true, err
	default:
		return false, nil
	}
}

func _GetOneResponse_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GetOneResponse)
	// discount
	switch x := m.Discount.(type) {
	case *GetOneResponse_DiscountForAll:
		s := proto.Size(x.DiscountForAll)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GetOneResponse_DiscountForOne:
		s := proto.Size(x.DiscountForOne)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GetOneResponse_DiscountForSet:
		s := proto.Size(x.DiscountForSet)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GetOneResponse_DiscountForBuyAForB:
		s := proto.Size(x.DiscountForBuyAForB)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GetOneResponse_DiscountForBuyXGetOne:
		s := proto.Size(x.DiscountForBuyXGetOne)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GetOneResponse_DiscountForBuyXGetMore:
		s := proto.Size(x.DiscountForBuyXGetMore)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GetOneResponse_DiscountForBuyXGetTotal:
		s := proto.Size(x.DiscountForBuyXGetTotal)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type DiscountForAll struct {
	Base                 *DiscountBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DiscountForAll) Reset()         { *m = DiscountForAll{} }
func (m *DiscountForAll) String() string { return proto.CompactTextString(m) }
func (*DiscountForAll) ProtoMessage()    {}
func (*DiscountForAll) Descriptor() ([]byte, []int) {
	return fileDescriptor_d27f2fd5df31734b, []int{3}
}

func (m *DiscountForAll) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscountForAll.Unmarshal(m, b)
}
func (m *DiscountForAll) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscountForAll.Marshal(b, m, deterministic)
}
func (m *DiscountForAll) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscountForAll.Merge(m, src)
}
func (m *DiscountForAll) XXX_Size() int {
	return xxx_messageInfo_DiscountForAll.Size(m)
}
func (m *DiscountForAll) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscountForAll.DiscardUnknown(m)
}

var xxx_messageInfo_DiscountForAll proto.InternalMessageInfo

func (m *DiscountForAll) GetBase() *DiscountBase {
	if m != nil {
		return m.Base
	}
	return nil
}

type CreateForAllRequest struct {
	TenantID             uint64          `protobuf:"varint,1,opt,name=tenantID,proto3" json:"tenantID,omitempty"`
	DiscountForAll       *DiscountForAll `protobuf:"bytes,2,opt,name=discountForAll,proto3" json:"discountForAll,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateForAllRequest) Reset()         { *m = CreateForAllRequest{} }
func (m *CreateForAllRequest) String() string { return proto.CompactTextString(m) }
func (*CreateForAllRequest) ProtoMessage()    {}
func (*CreateForAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d27f2fd5df31734b, []int{4}
}

func (m *CreateForAllRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateForAllRequest.Unmarshal(m, b)
}
func (m *CreateForAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateForAllRequest.Marshal(b, m, deterministic)
}
func (m *CreateForAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateForAllRequest.Merge(m, src)
}
func (m *CreateForAllRequest) XXX_Size() int {
	return xxx_messageInfo_CreateForAllRequest.Size(m)
}
func (m *CreateForAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateForAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateForAllRequest proto.InternalMessageInfo

func (m *CreateForAllRequest) GetTenantID() uint64 {
	if m != nil {
		return m.TenantID
	}
	return 0
}

func (m *CreateForAllRequest) GetDiscountForAll() *DiscountForAll {
	if m != nil {
		return m.DiscountForAll
	}
	return nil
}

type CreateResponse struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d27f2fd5df31734b, []int{5}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DiscountForOne struct {
	Base                 *DiscountBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	PrdouctID            uint64        `protobuf:"varint,2,opt,name=prdouctID,proto3" json:"prdouctID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DiscountForOne) Reset()         { *m = DiscountForOne{} }
func (m *DiscountForOne) String() string { return proto.CompactTextString(m) }
func (*DiscountForOne) ProtoMessage()    {}
func (*DiscountForOne) Descriptor() ([]byte, []int) {
	return fileDescriptor_d27f2fd5df31734b, []int{6}
}

func (m *DiscountForOne) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscountForOne.Unmarshal(m, b)
}
func (m *DiscountForOne) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscountForOne.Marshal(b, m, deterministic)
}
func (m *DiscountForOne) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscountForOne.Merge(m, src)
}
func (m *DiscountForOne) XXX_Size() int {
	return xxx_messageInfo_DiscountForOne.Size(m)
}
func (m *DiscountForOne) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscountForOne.DiscardUnknown(m)
}

var xxx_messageInfo_DiscountForOne proto.InternalMessageInfo

func (m *DiscountForOne) GetBase() *DiscountBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *DiscountForOne) GetPrdouctID() uint64 {
	if m != nil {
		return m.PrdouctID
	}
	return 0
}

type CreateForOneRequest struct {
	TenantID             uint64          `protobuf:"varint,1,opt,name=tenantID,proto3" json:"tenantID,omitempty"`
	DiscountForOne       *DiscountForOne `protobuf:"bytes,2,opt,name=discountForOne,proto3" json:"discountForOne,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateForOneRequest) Reset()         { *m = CreateForOneRequest{} }
func (m *CreateForOneRequest) String() string { return proto.CompactTextString(m) }
func (*CreateForOneRequest) ProtoMessage()    {}
func (*CreateForOneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d27f2fd5df31734b, []int{7}
}

func (m *CreateForOneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateForOneRequest.Unmarshal(m, b)
}
func (m *CreateForOneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateForOneRequest.Marshal(b, m, deterministic)
}
func (m *CreateForOneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateForOneRequest.Merge(m, src)
}
func (m *CreateForOneRequest) XXX_Size() int {
	return xxx_messageInfo_CreateForOneRequest.Size(m)
}
func (m *CreateForOneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateForOneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateForOneRequest proto.InternalMessageInfo

func (m *CreateForOneRequest) GetTenantID() uint64 {
	if m != nil {
		return m.TenantID
	}
	return 0
}

func (m *CreateForOneRequest) GetDiscountForOne() *DiscountForOne {
	if m != nil {
		return m.DiscountForOne
	}
	return nil
}

type DiscountForSet struct {
	Base                 *DiscountBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	PrdouctIDs           []uint64      `protobuf:"varint,2,rep,packed,name=prdouctIDs,proto3" json:"prdouctIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DiscountForSet) Reset()         { *m = DiscountForSet{} }
func (m *DiscountForSet) String() string { return proto.CompactTextString(m) }
func (*DiscountForSet) ProtoMessage()    {}
func (*DiscountForSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_d27f2fd5df31734b, []int{8}
}

func (m *DiscountForSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscountForSet.Unmarshal(m, b)
}
func (m *DiscountForSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscountForSet.Marshal(b, m, deterministic)
}
func (m *DiscountForSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscountForSet.Merge(m, src)
}
func (m *DiscountForSet) XXX_Size() int {
	return xxx_messageInfo_DiscountForSet.Size(m)
}
func (m *DiscountForSet) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscountForSet.DiscardUnknown(m)
}

var xxx_messageInfo_DiscountForSet proto.InternalMessageInfo

func (m *DiscountForSet) GetBase() *DiscountBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *DiscountForSet) GetPrdouctIDs() []uint64 {
	if m != nil {
		return m.PrdouctIDs
	}
	return nil
}

type CreateForSetRequest struct {
	TenantID             uint64          `protobuf:"varint,1,opt,name=tenantID,proto3" json:"tenantID,omitempty"`
	DiscountForSet       *DiscountForSet `protobuf:"bytes,2,opt,name=discountForSet,proto3" json:"discountForSet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CreateForSetRequest) Reset()         { *m = CreateForSetRequest{} }
func (m *CreateForSetRequest) String() string { return proto.CompactTextString(m) }
func (*CreateForSetRequest) ProtoMessage()    {}
func (*CreateForSetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d27f2fd5df31734b, []int{9}
}

func (m *CreateForSetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateForSetRequest.Unmarshal(m, b)
}
func (m *CreateForSetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateForSetRequest.Marshal(b, m, deterministic)
}
func (m *CreateForSetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateForSetRequest.Merge(m, src)
}
func (m *CreateForSetRequest) XXX_Size() int {
	return xxx_messageInfo_CreateForSetRequest.Size(m)
}
func (m *CreateForSetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateForSetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateForSetRequest proto.InternalMessageInfo

func (m *CreateForSetRequest) GetTenantID() uint64 {
	if m != nil {
		return m.TenantID
	}
	return 0
}

func (m *CreateForSetRequest) GetDiscountForSet() *DiscountForSet {
	if m != nil {
		return m.DiscountForSet
	}
	return nil
}

type DiscountForBuyAForB struct {
	Base                 *DiscountBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	PrdouctAID           uint64        `protobuf:"varint,2,opt,name=prdouctAID,proto3" json:"prdouctAID,omitempty"`
	PrdouctBID           uint64        `protobuf:"varint,3,opt,name=prdouctBID,proto3" json:"prdouctBID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DiscountForBuyAForB) Reset()         { *m = DiscountForBuyAForB{} }
func (m *DiscountForBuyAForB) String() string { return proto.CompactTextString(m) }
func (*DiscountForBuyAForB) ProtoMessage()    {}
func (*DiscountForBuyAForB) Descriptor() ([]byte, []int) {
	return fileDescriptor_d27f2fd5df31734b, []int{10}
}

func (m *DiscountForBuyAForB) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscountForBuyAForB.Unmarshal(m, b)
}
func (m *DiscountForBuyAForB) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscountForBuyAForB.Marshal(b, m, deterministic)
}
func (m *DiscountForBuyAForB) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscountForBuyAForB.Merge(m, src)
}
func (m *DiscountForBuyAForB) XXX_Size() int {
	return xxx_messageInfo_DiscountForBuyAForB.Size(m)
}
func (m *DiscountForBuyAForB) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscountForBuyAForB.DiscardUnknown(m)
}

var xxx_messageInfo_DiscountForBuyAForB proto.InternalMessageInfo

func (m *DiscountForBuyAForB) GetBase() *DiscountBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *DiscountForBuyAForB) GetPrdouctAID() uint64 {
	if m != nil {
		return m.PrdouctAID
	}
	return 0
}

func (m *DiscountForBuyAForB) GetPrdouctBID() uint64 {
	if m != nil {
		return m.PrdouctBID
	}
	return 0
}

type CreateForBuyAForBRequest struct {
	TenantID             uint64               `protobuf:"varint,1,opt,name=tenantID,proto3" json:"tenantID,omitempty"`
	DiscountForBuyAForB  *DiscountForBuyAForB `protobuf:"bytes,2,opt,name=discountForBuyAForB,proto3" json:"discountForBuyAForB,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateForBuyAForBRequest) Reset()         { *m = CreateForBuyAForBRequest{} }
func (m *CreateForBuyAForBRequest) String() string { return proto.CompactTextString(m) }
func (*CreateForBuyAForBRequest) ProtoMessage()    {}
func (*CreateForBuyAForBRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d27f2fd5df31734b, []int{11}
}

func (m *CreateForBuyAForBRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateForBuyAForBRequest.Unmarshal(m, b)
}
func (m *CreateForBuyAForBRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateForBuyAForBRequest.Marshal(b, m, deterministic)
}
func (m *CreateForBuyAForBRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateForBuyAForBRequest.Merge(m, src)
}
func (m *CreateForBuyAForBRequest) XXX_Size() int {
	return xxx_messageInfo_CreateForBuyAForBRequest.Size(m)
}
func (m *CreateForBuyAForBRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateForBuyAForBRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateForBuyAForBRequest proto.InternalMessageInfo

func (m *CreateForBuyAForBRequest) GetTenantID() uint64 {
	if m != nil {
		return m.TenantID
	}
	return 0
}

func (m *CreateForBuyAForBRequest) GetDiscountForBuyAForB() *DiscountForBuyAForB {
	if m != nil {
		return m.DiscountForBuyAForB
	}
	return nil
}

type DiscountForBuyXGet struct {
	Base                 *DiscountBase `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	PrdouctID            uint64        `protobuf:"varint,2,opt,name=prdouctID,proto3" json:"prdouctID,omitempty"`
	XNum                 uint32        `protobuf:"varint,3,opt,name=xNum,proto3" json:"xNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *DiscountForBuyXGet) Reset()         { *m = DiscountForBuyXGet{} }
func (m *DiscountForBuyXGet) String() string { return proto.CompactTextString(m) }
func (*DiscountForBuyXGet) ProtoMessage()    {}
func (*DiscountForBuyXGet) Descriptor() ([]byte, []int) {
	return fileDescriptor_d27f2fd5df31734b, []int{12}
}

func (m *DiscountForBuyXGet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiscountForBuyXGet.Unmarshal(m, b)
}
func (m *DiscountForBuyXGet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiscountForBuyXGet.Marshal(b, m, deterministic)
}
func (m *DiscountForBuyXGet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiscountForBuyXGet.Merge(m, src)
}
func (m *DiscountForBuyXGet) XXX_Size() int {
	return xxx_messageInfo_DiscountForBuyXGet.Size(m)
}
func (m *DiscountForBuyXGet) XXX_DiscardUnknown() {
	xxx_messageInfo_DiscountForBuyXGet.DiscardUnknown(m)
}

var xxx_messageInfo_DiscountForBuyXGet proto.InternalMessageInfo

func (m *DiscountForBuyXGet) GetBase() *DiscountBase {
	if m != nil {
		return m.Base
	}
	return nil
}

func (m *DiscountForBuyXGet) GetPrdouctID() uint64 {
	if m != nil {
		return m.PrdouctID
	}
	return 0
}

func (m *DiscountForBuyXGet) GetXNum() uint32 {
	if m != nil {
		return m.XNum
	}
	return 0
}

type CreateForBuyXGetRequest struct {
	TenantID             uint64              `protobuf:"varint,1,opt,name=tenantID,proto3" json:"tenantID,omitempty"`
	DiscountForBuyXGet   *DiscountForBuyXGet `protobuf:"bytes,2,opt,name=discountForBuyXGet,proto3" json:"discountForBuyXGet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CreateForBuyXGetRequest) Reset()         { *m = CreateForBuyXGetRequest{} }
func (m *CreateForBuyXGetRequest) String() string { return proto.CompactTextString(m) }
func (*CreateForBuyXGetRequest) ProtoMessage()    {}
func (*CreateForBuyXGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d27f2fd5df31734b, []int{13}
}

func (m *CreateForBuyXGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateForBuyXGetRequest.Unmarshal(m, b)
}
func (m *CreateForBuyXGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateForBuyXGetRequest.Marshal(b, m, deterministic)
}
func (m *CreateForBuyXGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateForBuyXGetRequest.Merge(m, src)
}
func (m *CreateForBuyXGetRequest) XXX_Size() int {
	return xxx_messageInfo_CreateForBuyXGetRequest.Size(m)
}
func (m *CreateForBuyXGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateForBuyXGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateForBuyXGetRequest proto.InternalMessageInfo

func (m *CreateForBuyXGetRequest) GetTenantID() uint64 {
	if m != nil {
		return m.TenantID
	}
	return 0
}

func (m *CreateForBuyXGetRequest) GetDiscountForBuyXGet() *DiscountForBuyXGet {
	if m != nil {
		return m.DiscountForBuyXGet
	}
	return nil
}

func init() {
	proto.RegisterEnum("pb.DiscountBase_Kind", DiscountBase_Kind_name, DiscountBase_Kind_value)
	proto.RegisterType((*DiscountBase)(nil), "pb.DiscountBase")
	proto.RegisterType((*GetOneRequest)(nil), "pb.GetOneRequest")
	proto.RegisterType((*GetOneResponse)(nil), "pb.GetOneResponse")
	proto.RegisterType((*DiscountForAll)(nil), "pb.DiscountForAll")
	proto.RegisterType((*CreateForAllRequest)(nil), "pb.CreateForAllRequest")
	proto.RegisterType((*CreateResponse)(nil), "pb.CreateResponse")
	proto.RegisterType((*DiscountForOne)(nil), "pb.DiscountForOne")
	proto.RegisterType((*CreateForOneRequest)(nil), "pb.CreateForOneRequest")
	proto.RegisterType((*DiscountForSet)(nil), "pb.DiscountForSet")
	proto.RegisterType((*CreateForSetRequest)(nil), "pb.CreateForSetRequest")
	proto.RegisterType((*DiscountForBuyAForB)(nil), "pb.DiscountForBuyAForB")
	proto.RegisterType((*CreateForBuyAForBRequest)(nil), "pb.CreateForBuyAForBRequest")
	proto.RegisterType((*DiscountForBuyXGet)(nil), "pb.DiscountForBuyXGet")
	proto.RegisterType((*CreateForBuyXGetRequest)(nil), "pb.CreateForBuyXGetRequest")
}

func init() { proto.RegisterFile("proto/discount.proto", fileDescriptor_d27f2fd5df31734b) }

var fileDescriptor_d27f2fd5df31734b = []byte{
	// 796 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x4f, 0x6f, 0xda, 0x4e,
	0x10, 0xc5, 0xc6, 0x01, 0x32, 0x24, 0xfc, 0xc8, 0xe6, 0x9f, 0xc5, 0x2f, 0x6a, 0x2d, 0xab, 0x07,
	0x7a, 0x01, 0x89, 0x4a, 0x39, 0xa4, 0x3d, 0x14, 0x0a, 0x09, 0x28, 0x01, 0xaa, 0x85, 0x34, 0xbd,
	0x9a, 0x78, 0x1b, 0x59, 0x05, 0x9b, 0xda, 0x4b, 0xd4, 0xaa, 0xea, 0xa1, 0x1f, 0xa3, 0xea, 0xad,
	0x9f, 0xb4, 0xda, 0xc5, 0x26, 0xf6, 0xda, 0x24, 0x46, 0xea, 0x09, 0xef, 0xcc, 0xbc, 0x99, 0x7d,
	0xbb, 0xf3, 0x66, 0x81, 0x83, 0xb9, 0xeb, 0x50, 0xa7, 0x6e, 0x5a, 0xde, 0xad, 0xb3, 0xb0, 0x69,
	0x8d, 0x2f, 0x91, 0x3c, 0x9f, 0x54, 0x9e, 0xdf, 0x39, 0xce, 0xdd, 0x94, 0xd4, 0xb9, 0x65, 0xb2,
	0xf8, 0x54, 0xa7, 0xd6, 0x8c, 0x78, 0xd4, 0x98, 0xcd, 0x97, 0x41, 0xfa, 0x1f, 0x19, 0x76, 0xda,
	0x3e, 0xae, 0x65, 0x78, 0x04, 0xbd, 0x04, 0xe5, 0xb3, 0x65, 0x9b, 0xaa, 0xa4, 0x49, 0xd5, 0x52,
	0xe3, 0xb0, 0x36, 0x9f, 0xd4, 0xc2, 0xfe, 0xda, 0xa5, 0x65, 0x9b, 0x98, 0x87, 0x20, 0x15, 0x72,
	0xc6, 0x8c, 0x39, 0x54, 0x59, 0x93, 0xaa, 0xbb, 0xdd, 0x0c, 0xf6, 0xd7, 0xe8, 0x00, 0x14, 0xd7,
	0xa0, 0x44, 0xcd, 0x6a, 0x52, 0x55, 0xee, 0x66, 0x30, 0x5f, 0x21, 0x15, 0xf2, 0x33, 0xe2, 0x79,
	0xc6, 0x1d, 0x51, 0x15, 0x4d, 0xaa, 0x6e, 0xe3, 0x60, 0x89, 0x4e, 0xa1, 0x60, 0x12, 0xc3, 0x9c,
	0x5a, 0x36, 0x51, 0xb7, 0x34, 0xa9, 0x5a, 0x6c, 0x54, 0x6a, 0xcb, 0x9d, 0xd7, 0x82, 0x9d, 0xd7,
	0xc6, 0xc1, 0xce, 0xf1, 0x2a, 0x16, 0x55, 0xa0, 0x60, 0x79, 0x7d, 0x32, 0x9b, 0x10, 0x57, 0xcd,
	0x69, 0x52, 0xb5, 0x80, 0x57, 0x6b, 0xfd, 0x2d, 0x28, 0x6c, 0xaf, 0xa8, 0x08, 0xf9, 0xeb, 0xc1,
	0xe5, 0x60, 0x78, 0x33, 0x28, 0x67, 0x10, 0x40, 0x6e, 0x30, 0xc4, 0xfd, 0xe6, 0x55, 0x59, 0x42,
	0x79, 0xc8, 0x0e, 0x3a, 0x37, 0x65, 0x99, 0x19, 0x87, 0xd7, 0xe3, 0xab, 0xce, 0xb8, 0x9c, 0x65,
	0xdf, 0xfd, 0x4e, 0xbf, 0xd5, 0xc1, 0x65, 0xa5, 0x95, 0x87, 0xad, 0x7b, 0x63, 0xba, 0x20, 0x7a,
	0x0f, 0x76, 0x2f, 0x08, 0x1d, 0xda, 0x04, 0x93, 0x2f, 0x0b, 0xe2, 0x51, 0x56, 0x97, 0x12, 0xdb,
	0xb0, 0x69, 0xaf, 0xcd, 0x0f, 0x4a, 0xc1, 0xab, 0x35, 0x3a, 0x81, 0xed, 0xb9, 0x6b, 0x3a, 0x8b,
	0x5b, 0xe6, 0x94, 0xb9, 0xf3, 0xc1, 0xa0, 0xff, 0x52, 0xa0, 0x14, 0xe4, 0xf2, 0xe6, 0x8e, 0xed,
	0x11, 0xf4, 0x06, 0x4a, 0xc1, 0xcd, 0x9d, 0x3b, 0x6e, 0x73, 0x3a, 0xe5, 0x29, 0x8b, 0x0d, 0x14,
	0x3e, 0xfb, 0xa5, 0xa7, 0x9b, 0xc1, 0x42, 0xac, 0x80, 0x1e, 0xda, 0x84, 0xd7, 0x8c, 0xa3, 0x87,
	0x36, 0x11, 0xd0, 0x43, 0x5b, 0xac, 0x3d, 0x22, 0x94, 0x5f, 0x59, 0x1c, 0x3d, 0x22, 0x54, 0x40,
	0x8f, 0x08, 0x45, 0x97, 0xb0, 0x1f, 0xb2, 0xb4, 0x16, 0xdf, 0x9a, 0xec, 0x87, 0x5f, 0x6e, 0xb1,
	0x71, 0x2c, 0xa4, 0x08, 0xdc, 0xdd, 0x0c, 0x4e, 0x42, 0xa1, 0x01, 0x1c, 0x46, 0xcd, 0x1f, 0x97,
	0xe7, 0xe4, 0x37, 0xc4, 0x51, 0x3c, 0x1d, 0x0b, 0xe8, 0x66, 0x70, 0x32, 0x0c, 0xbd, 0x87, 0xa3,
	0xb8, 0xa3, 0xef, 0xb8, 0x84, 0x77, 0xca, 0x63, 0x09, 0xd7, 0xe0, 0x10, 0x86, 0xe3, 0xb8, 0x67,
	0xec, 0x50, 0x63, 0xaa, 0xe6, 0x9f, 0x48, 0xb9, 0x0e, 0xd8, 0x02, 0x28, 0x04, 0x2e, 0xfd, 0x14,
	0x4a, 0xd1, 0xeb, 0x46, 0x2f, 0x40, 0x99, 0x18, 0x1e, 0xf1, 0x1b, 0xa2, 0x2c, 0x8a, 0x11, 0x73,
	0xaf, 0x3e, 0x83, 0xfd, 0x77, 0x2e, 0x31, 0x28, 0x59, 0xa2, 0xd2, 0x34, 0xe9, 0x59, 0xac, 0xe7,
	0xe4, 0x75, 0x3d, 0x27, 0x76, 0x9c, 0xae, 0x41, 0x69, 0x59, 0x6e, 0xd5, 0xc1, 0x25, 0x90, 0x2d,
	0xd3, 0xaf, 0x21, 0x5b, 0xa6, 0x3e, 0x8e, 0x10, 0x61, 0x97, 0x91, 0x8a, 0xc8, 0x13, 0xd2, 0x09,
	0xd3, 0x4c, 0xa9, 0xc5, 0xb3, 0xf4, 0xe2, 0x10, 0xa5, 0xa1, 0x7f, 0x88, 0x90, 0x60, 0xed, 0x9e,
	0x8e, 0xc4, 0x33, 0x80, 0xd5, 0x9e, 0x3d, 0x55, 0xd6, 0xb2, 0x55, 0x05, 0x87, 0x2c, 0x11, 0x1a,
	0x23, 0x42, 0x37, 0xa7, 0xc1, 0x54, 0x2a, 0xaf, 0x53, 0xa9, 0xa8, 0x51, 0xfd, 0x3b, 0xec, 0x27,
	0x88, 0x70, 0x63, 0x2e, 0xcd, 0xd5, 0x8d, 0x84, 0x2c, 0x21, 0x7f, 0xab, 0xd7, 0xe6, 0xa3, 0xe3,
	0xc1, 0xdf, 0xea, 0xb5, 0xf5, 0x9f, 0x12, 0xa8, 0x2b, 0xb2, 0x41, 0xed, 0x34, 0x8c, 0x7b, 0xc9,
	0x93, 0x45, 0x7e, 0x74, 0xb2, 0x24, 0xce, 0x15, 0x7d, 0x0a, 0x28, 0x2e, 0xc9, 0x7f, 0xd1, 0x90,
	0x08, 0x81, 0xf2, 0x75, 0xb0, 0x98, 0x71, 0xde, 0xbb, 0x98, 0x7f, 0xeb, 0x3f, 0xe0, 0x38, 0x4c,
	0x98, 0xd5, 0x4a, 0xc3, 0xf7, 0x1c, 0x50, 0x7c, 0x42, 0xf8, 0x74, 0xd7, 0x4c, 0x15, 0x9c, 0x80,
	0x68, 0xfc, 0x56, 0xe0, 0xbf, 0x20, 0x74, 0x44, 0xdc, 0x7b, 0xeb, 0x96, 0xa0, 0x3a, 0xe4, 0xfc,
	0x91, 0xb8, 0xc7, 0x32, 0x45, 0x5e, 0xb2, 0x0a, 0x0a, 0x9b, 0x7c, 0x39, 0xbf, 0x86, 0x9d, 0xf0,
	0x3c, 0x41, 0xfc, 0xbc, 0x13, 0x26, 0xcc, 0x12, 0x2c, 0xcc, 0x82, 0x30, 0x98, 0xd5, 0x8c, 0x82,
	0xc5, 0xca, 0x8f, 0x80, 0x99, 0xe2, 0xa2, 0xe0, 0x07, 0xb5, 0x24, 0x82, 0x3b, 0xb0, 0x17, 0xeb,
	0x35, 0x74, 0x12, 0xc9, 0x20, 0xb4, 0x60, 0x62, 0x9a, 0xf3, 0x90, 0x3e, 0x43, 0xcf, 0xc9, 0xff,
	0x62, 0xa2, 0xd0, 0xd5, 0x26, 0xe6, 0xb9, 0x80, 0x03, 0x31, 0x9c, 0xbf, 0x22, 0x1b, 0x27, 0xea,
	0xc2, 0xa1, 0x18, 0xce, 0xdf, 0x8e, 0x8d, 0x33, 0x4d, 0x72, 0xfc, 0xcf, 0xd4, 0xab, 0xbf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x0d, 0x73, 0x98, 0x10, 0x30, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// DiscountServiceClient is the client API for DiscountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DiscountServiceClient interface {
	GetOne(ctx context.Context, in *GetOneRequest, opts ...grpc.CallOption) (*GetOneResponse, error)
	CreateForAll(ctx context.Context, in *CreateForAllRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	CreateForOne(ctx context.Context, in *CreateForOneRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	CreateForSet(ctx context.Context, in *CreateForSetRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	CreateForBuyAForB(ctx context.Context, in *CreateForBuyAForBRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	CreateForBuyXGetOne(ctx context.Context, in *CreateForBuyXGetRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	CreateForBuyXGetMore(ctx context.Context, in *CreateForBuyXGetRequest, opts ...grpc.CallOption) (*CreateResponse, error)
	CreateForBuyXGetTotal(ctx context.Context, in *CreateForBuyXGetRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type discountServiceClient struct {
	cc *grpc.ClientConn
}

func NewDiscountServiceClient(cc *grpc.ClientConn) DiscountServiceClient {
	return &discountServiceClient{cc}
}

func (c *discountServiceClient) GetOne(ctx context.Context, in *GetOneRequest, opts ...grpc.CallOption) (*GetOneResponse, error) {
	out := new(GetOneResponse)
	err := c.cc.Invoke(ctx, "/pb.DiscountService/GetOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discountServiceClient) CreateForAll(ctx context.Context, in *CreateForAllRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/pb.DiscountService/CreateForAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discountServiceClient) CreateForOne(ctx context.Context, in *CreateForOneRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/pb.DiscountService/CreateForOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discountServiceClient) CreateForSet(ctx context.Context, in *CreateForSetRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/pb.DiscountService/CreateForSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discountServiceClient) CreateForBuyAForB(ctx context.Context, in *CreateForBuyAForBRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/pb.DiscountService/CreateForBuyAForB", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discountServiceClient) CreateForBuyXGetOne(ctx context.Context, in *CreateForBuyXGetRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/pb.DiscountService/CreateForBuyXGetOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discountServiceClient) CreateForBuyXGetMore(ctx context.Context, in *CreateForBuyXGetRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/pb.DiscountService/CreateForBuyXGetMore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discountServiceClient) CreateForBuyXGetTotal(ctx context.Context, in *CreateForBuyXGetRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/pb.DiscountService/CreateForBuyXGetTotal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscountServiceServer is the server API for DiscountService service.
type DiscountServiceServer interface {
	GetOne(context.Context, *GetOneRequest) (*GetOneResponse, error)
	CreateForAll(context.Context, *CreateForAllRequest) (*CreateResponse, error)
	CreateForOne(context.Context, *CreateForOneRequest) (*CreateResponse, error)
	CreateForSet(context.Context, *CreateForSetRequest) (*CreateResponse, error)
	CreateForBuyAForB(context.Context, *CreateForBuyAForBRequest) (*CreateResponse, error)
	CreateForBuyXGetOne(context.Context, *CreateForBuyXGetRequest) (*CreateResponse, error)
	CreateForBuyXGetMore(context.Context, *CreateForBuyXGetRequest) (*CreateResponse, error)
	CreateForBuyXGetTotal(context.Context, *CreateForBuyXGetRequest) (*CreateResponse, error)
}

func RegisterDiscountServiceServer(s *grpc.Server, srv DiscountServiceServer) {
	s.RegisterService(&_DiscountService_serviceDesc, srv)
}

func _DiscountService_GetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscountServiceServer).GetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.DiscountService/GetOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscountServiceServer).GetOne(ctx, req.(*GetOneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscountService_CreateForAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateForAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscountServiceServer).CreateForAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.DiscountService/CreateForAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscountServiceServer).CreateForAll(ctx, req.(*CreateForAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscountService_CreateForOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateForOneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscountServiceServer).CreateForOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.DiscountService/CreateForOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscountServiceServer).CreateForOne(ctx, req.(*CreateForOneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscountService_CreateForSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateForSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscountServiceServer).CreateForSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.DiscountService/CreateForSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscountServiceServer).CreateForSet(ctx, req.(*CreateForSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscountService_CreateForBuyAForB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateForBuyAForBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscountServiceServer).CreateForBuyAForB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.DiscountService/CreateForBuyAForB",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscountServiceServer).CreateForBuyAForB(ctx, req.(*CreateForBuyAForBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscountService_CreateForBuyXGetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateForBuyXGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscountServiceServer).CreateForBuyXGetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.DiscountService/CreateForBuyXGetOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscountServiceServer).CreateForBuyXGetOne(ctx, req.(*CreateForBuyXGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscountService_CreateForBuyXGetMore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateForBuyXGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscountServiceServer).CreateForBuyXGetMore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.DiscountService/CreateForBuyXGetMore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscountServiceServer).CreateForBuyXGetMore(ctx, req.(*CreateForBuyXGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscountService_CreateForBuyXGetTotal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateForBuyXGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscountServiceServer).CreateForBuyXGetTotal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.DiscountService/CreateForBuyXGetTotal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscountServiceServer).CreateForBuyXGetTotal(ctx, req.(*CreateForBuyXGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DiscountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.DiscountService",
	HandlerType: (*DiscountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOne",
			Handler:    _DiscountService_GetOne_Handler,
		},
		{
			MethodName: "CreateForAll",
			Handler:    _DiscountService_CreateForAll_Handler,
		},
		{
			MethodName: "CreateForOne",
			Handler:    _DiscountService_CreateForOne_Handler,
		},
		{
			MethodName: "CreateForSet",
			Handler:    _DiscountService_CreateForSet_Handler,
		},
		{
			MethodName: "CreateForBuyAForB",
			Handler:    _DiscountService_CreateForBuyAForB_Handler,
		},
		{
			MethodName: "CreateForBuyXGetOne",
			Handler:    _DiscountService_CreateForBuyXGetOne_Handler,
		},
		{
			MethodName: "CreateForBuyXGetMore",
			Handler:    _DiscountService_CreateForBuyXGetMore_Handler,
		},
		{
			MethodName: "CreateForBuyXGetTotal",
			Handler:    _DiscountService_CreateForBuyXGetTotal_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/discount.proto",
}
