// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/gift.proto

package pb

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

func init() { proto.RegisterFile("proto/gift.proto", fileDescriptor_11a75a5cd399726e) }

var fileDescriptor_11a75a5cd399726e = []byte{
	// 63 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xcf, 0x4c, 0x2b, 0xd1, 0x03, 0x33, 0x85, 0x98, 0x0a, 0x92, 0x8c, 0x78, 0xb9,
	0xb8, 0xdd, 0x33, 0xd3, 0x4a, 0x82, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x93, 0xd8, 0xc0, 0x32,
	0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x51, 0x3a, 0x30, 0x2d, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GiftServiceClient is the client API for GiftService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GiftServiceClient interface {
}

type giftServiceClient struct {
	cc *grpc.ClientConn
}

func NewGiftServiceClient(cc *grpc.ClientConn) GiftServiceClient {
	return &giftServiceClient{cc}
}

// GiftServiceServer is the server API for GiftService service.
type GiftServiceServer interface {
}

func RegisterGiftServiceServer(s *grpc.Server, srv GiftServiceServer) {
	s.RegisterService(&_GiftService_serviceDesc, srv)
}

var _GiftService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GiftService",
	HandlerType: (*GiftServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "proto/gift.proto",
}
